create table transactions
(
    amount                 numeric(38, 2) not null,
    created_at             timestamp(6)   not null default current_timestamp,
    destination_account_id bigint         not null,
    id                     bigint generated by default as identity,
    source_account_id      bigint         not null,

    primary key (id),
    constraint fk_source_account_id
        foreign key (source_account_id)
            references accounts (id),

    constraint fk_destination_account_id
        foreign key (destination_account_id)
            references accounts (id)
)